"""
Adhan Connect — Données du Coran complet (114 sourates).
Métadonnées seulement. Les versets sont fetchés depuis Al-Quran Cloud API à la demande.
"""

SURAHS_114 = [
    {"n": 1, "ar": "الفاتحة", "tr": "Al-Fatiha", "fr": "L'Ouverture", "verses": 7, "type": "Mecquoise"},
    {"n": 2, "ar": "البقرة", "tr": "Al-Baqarah", "fr": "La Vache", "verses": 286, "type": "Médinoise"},
    {"n": 3, "ar": "آل عمران", "tr": "Aal-Imran", "fr": "La Famille d'Imran", "verses": 200, "type": "Médinoise"},
    {"n": 4, "ar": "النساء", "tr": "An-Nisa", "fr": "Les Femmes", "verses": 176, "type": "Médinoise"},
    {"n": 5, "ar": "المائدة", "tr": "Al-Ma'idah", "fr": "La Table Servie", "verses": 120, "type": "Médinoise"},
    {"n": 6, "ar": "الأنعام", "tr": "Al-An'am", "fr": "Les Bestiaux", "verses": 165, "type": "Mecquoise"},
    {"n": 7, "ar": "الأعراف", "tr": "Al-A'raf", "fr": "Les Murailles", "verses": 206, "type": "Mecquoise"},
    {"n": 8, "ar": "الأنفال", "tr": "Al-Anfal", "fr": "Le Butin", "verses": 75, "type": "Médinoise"},
    {"n": 9, "ar": "التوبة", "tr": "At-Tawbah", "fr": "Le Repentir", "verses": 129, "type": "Médinoise"},
    {"n": 10, "ar": "يونس", "tr": "Yunus", "fr": "Jonas", "verses": 109, "type": "Mecquoise"},
    {"n": 11, "ar": "هود", "tr": "Hud", "fr": "Hud", "verses": 123, "type": "Mecquoise"},
    {"n": 12, "ar": "يوسف", "tr": "Yusuf", "fr": "Joseph", "verses": 111, "type": "Mecquoise"},
    {"n": 13, "ar": "الرعد", "tr": "Ar-Ra'd", "fr": "Le Tonnerre", "verses": 43, "type": "Médinoise"},
    {"n": 14, "ar": "إبراهيم", "tr": "Ibrahim", "fr": "Abraham", "verses": 52, "type": "Mecquoise"},
    {"n": 15, "ar": "الحجر", "tr": "Al-Hijr", "fr": "Al-Hijr", "verses": 99, "type": "Mecquoise"},
    {"n": 16, "ar": "النحل", "tr": "An-Nahl", "fr": "Les Abeilles", "verses": 128, "type": "Mecquoise"},
    {"n": 17, "ar": "الإسراء", "tr": "Al-Isra", "fr": "Le Voyage Nocturne", "verses": 111, "type": "Mecquoise"},
    {"n": 18, "ar": "الكهف", "tr": "Al-Kahf", "fr": "La Caverne", "verses": 110, "type": "Mecquoise"},
    {"n": 19, "ar": "مريم", "tr": "Maryam", "fr": "Marie", "verses": 98, "type": "Mecquoise"},
    {"n": 20, "ar": "طه", "tr": "Ta-Ha", "fr": "Ta-Ha", "verses": 135, "type": "Mecquoise"},
    {"n": 21, "ar": "الأنبياء", "tr": "Al-Anbiya", "fr": "Les Prophètes", "verses": 112, "type": "Mecquoise"},
    {"n": 22, "ar": "الحج", "tr": "Al-Hajj", "fr": "Le Pèlerinage", "verses": 78, "type": "Médinoise"},
    {"n": 23, "ar": "المؤمنون", "tr": "Al-Mu'minun", "fr": "Les Croyants", "verses": 118, "type": "Mecquoise"},
    {"n": 24, "ar": "النور", "tr": "An-Nur", "fr": "La Lumière", "verses": 64, "type": "Médinoise"},
    {"n": 25, "ar": "الفرقان", "tr": "Al-Furqan", "fr": "Le Discernement", "verses": 77, "type": "Mecquoise"},
    {"n": 26, "ar": "الشعراء", "tr": "Ash-Shu'ara", "fr": "Les Poètes", "verses": 227, "type": "Mecquoise"},
    {"n": 27, "ar": "النمل", "tr": "An-Naml", "fr": "Les Fourmis", "verses": 93, "type": "Mecquoise"},
    {"n": 28, "ar": "القصص", "tr": "Al-Qasas", "fr": "Le Récit", "verses": 88, "type": "Mecquoise"},
    {"n": 29, "ar": "العنكبوت", "tr": "Al-'Ankabut", "fr": "L'Araignée", "verses": 69, "type": "Mecquoise"},
    {"n": 30, "ar": "الروم", "tr": "Ar-Rum", "fr": "Les Romains", "verses": 60, "type": "Mecquoise"},
    {"n": 31, "ar": "لقمان", "tr": "Luqman", "fr": "Luqman", "verses": 34, "type": "Mecquoise"},
    {"n": 32, "ar": "السجدة", "tr": "As-Sajdah", "fr": "La Prosternation", "verses": 30, "type": "Mecquoise"},
    {"n": 33, "ar": "الأحزاب", "tr": "Al-Ahzab", "fr": "Les Coalisés", "verses": 73, "type": "Médinoise"},
    {"n": 34, "ar": "سبأ", "tr": "Saba", "fr": "Saba", "verses": 54, "type": "Mecquoise"},
    {"n": 35, "ar": "فاطر", "tr": "Fatir", "fr": "Le Créateur", "verses": 45, "type": "Mecquoise"},
    {"n": 36, "ar": "يس", "tr": "Ya-Sin", "fr": "Ya-Sin", "verses": 83, "type": "Mecquoise"},
    {"n": 37, "ar": "الصافات", "tr": "As-Saffat", "fr": "Les Rangés", "verses": 182, "type": "Mecquoise"},
    {"n": 38, "ar": "ص", "tr": "Sad", "fr": "Sad", "verses": 88, "type": "Mecquoise"},
    {"n": 39, "ar": "الزمر", "tr": "Az-Zumar", "fr": "Les Groupes", "verses": 75, "type": "Mecquoise"},
    {"n": 40, "ar": "غافر", "tr": "Ghafir", "fr": "Le Pardonneur", "verses": 85, "type": "Mecquoise"},
    {"n": 41, "ar": "فصلت", "tr": "Fussilat", "fr": "Les Versets Détaillés", "verses": 54, "type": "Mecquoise"},
    {"n": 42, "ar": "الشورى", "tr": "Ash-Shura", "fr": "La Consultation", "verses": 53, "type": "Mecquoise"},
    {"n": 43, "ar": "الزخرف", "tr": "Az-Zukhruf", "fr": "L'Ornement", "verses": 89, "type": "Mecquoise"},
    {"n": 44, "ar": "الدخان", "tr": "Ad-Dukhan", "fr": "La Fumée", "verses": 59, "type": "Mecquoise"},
    {"n": 45, "ar": "الجاثية", "tr": "Al-Jathiyah", "fr": "L'Agenouillée", "verses": 37, "type": "Mecquoise"},
    {"n": 46, "ar": "الأحقاف", "tr": "Al-Ahqaf", "fr": "Al-Ahqaf", "verses": 35, "type": "Mecquoise"},
    {"n": 47, "ar": "محمد", "tr": "Muhammad", "fr": "Muhammad", "verses": 38, "type": "Médinoise"},
    {"n": 48, "ar": "الفتح", "tr": "Al-Fath", "fr": "La Victoire Éclatante", "verses": 29, "type": "Médinoise"},
    {"n": 49, "ar": "الحجرات", "tr": "Al-Hujurat", "fr": "Les Appartements", "verses": 18, "type": "Médinoise"},
    {"n": 50, "ar": "ق", "tr": "Qaf", "fr": "Qaf", "verses": 45, "type": "Mecquoise"},
    {"n": 51, "ar": "الذاريات", "tr": "Adh-Dhariyat", "fr": "Qui éparpillent", "verses": 60, "type": "Mecquoise"},
    {"n": 52, "ar": "الطور", "tr": "At-Tur", "fr": "Le Mont", "verses": 49, "type": "Mecquoise"},
    {"n": 53, "ar": "النجم", "tr": "An-Najm", "fr": "L'Étoile", "verses": 62, "type": "Mecquoise"},
    {"n": 54, "ar": "القمر", "tr": "Al-Qamar", "fr": "La Lune", "verses": 55, "type": "Mecquoise"},
    {"n": 55, "ar": "الرحمن", "tr": "Ar-Rahman", "fr": "Le Tout Miséricordieux", "verses": 78, "type": "Médinoise"},
    {"n": 56, "ar": "الواقعة", "tr": "Al-Waqi'ah", "fr": "L'Évènement", "verses": 96, "type": "Mecquoise"},
    {"n": 57, "ar": "الحديد", "tr": "Al-Hadid", "fr": "Le Fer", "verses": 29, "type": "Médinoise"},
    {"n": 58, "ar": "المجادلة", "tr": "Al-Mujadilah", "fr": "La Discussion", "verses": 22, "type": "Médinoise"},
    {"n": 59, "ar": "الحشر", "tr": "Al-Hashr", "fr": "L'Exode", "verses": 24, "type": "Médinoise"},
    {"n": 60, "ar": "الممتحنة", "tr": "Al-Mumtahanah", "fr": "L'Éprouvée", "verses": 13, "type": "Médinoise"},
    {"n": 61, "ar": "الصف", "tr": "As-Saff", "fr": "Le Rang", "verses": 14, "type": "Médinoise"},
    {"n": 62, "ar": "الجمعة", "tr": "Al-Jumu'ah", "fr": "Le Vendredi", "verses": 11, "type": "Médinoise"},
    {"n": 63, "ar": "المنافقون", "tr": "Al-Munafiqun", "fr": "Les Hypocrites", "verses": 11, "type": "Médinoise"},
    {"n": 64, "ar": "التغابن", "tr": "At-Taghabun", "fr": "La Grande Perte", "verses": 18, "type": "Médinoise"},
    {"n": 65, "ar": "الطلاق", "tr": "At-Talaq", "fr": "Le Divorce", "verses": 12, "type": "Médinoise"},
    {"n": 66, "ar": "التحريم", "tr": "At-Tahrim", "fr": "L'Interdiction", "verses": 12, "type": "Médinoise"},
    {"n": 67, "ar": "الملك", "tr": "Al-Mulk", "fr": "La Royauté", "verses": 30, "type": "Mecquoise"},
    {"n": 68, "ar": "القلم", "tr": "Al-Qalam", "fr": "La Plume", "verses": 52, "type": "Mecquoise"},
    {"n": 69, "ar": "الحاقة", "tr": "Al-Haqqah", "fr": "L'Inévitable", "verses": 52, "type": "Mecquoise"},
    {"n": 70, "ar": "المعارج", "tr": "Al-Ma'arij", "fr": "Les Voies d'Ascension", "verses": 44, "type": "Mecquoise"},
    {"n": 71, "ar": "نوح", "tr": "Nuh", "fr": "Noé", "verses": 28, "type": "Mecquoise"},
    {"n": 72, "ar": "الجن", "tr": "Al-Jinn", "fr": "Les Djinns", "verses": 28, "type": "Mecquoise"},
    {"n": 73, "ar": "المزمل", "tr": "Al-Muzzammil", "fr": "L'Enveloppé", "verses": 20, "type": "Mecquoise"},
    {"n": 74, "ar": "المدثر", "tr": "Al-Muddaththir", "fr": "Le Revêtu d'un Manteau", "verses": 56, "type": "Mecquoise"},
    {"n": 75, "ar": "القيامة", "tr": "Al-Qiyamah", "fr": "La Résurrection", "verses": 40, "type": "Mecquoise"},
    {"n": 76, "ar": "الإنسان", "tr": "Al-Insan", "fr": "L'Homme", "verses": 31, "type": "Médinoise"},
    {"n": 77, "ar": "المرسلات", "tr": "Al-Mursalat", "fr": "Les Envoyés", "verses": 50, "type": "Mecquoise"},
    {"n": 78, "ar": "النبأ", "tr": "An-Naba", "fr": "La Nouvelle", "verses": 40, "type": "Mecquoise"},
    {"n": 79, "ar": "النازعات", "tr": "An-Nazi'at", "fr": "Les Anges Arracheurs", "verses": 46, "type": "Mecquoise"},
    {"n": 80, "ar": "عبس", "tr": "'Abasa", "fr": "Il s'est Renfrogné", "verses": 42, "type": "Mecquoise"},
    {"n": 81, "ar": "التكوير", "tr": "At-Takwir", "fr": "L'Obscurcissement", "verses": 29, "type": "Mecquoise"},
    {"n": 82, "ar": "الانفطار", "tr": "Al-Infitar", "fr": "La Rupture", "verses": 19, "type": "Mecquoise"},
    {"n": 83, "ar": "المطففين", "tr": "Al-Mutaffifin", "fr": "Les Fraudeurs", "verses": 36, "type": "Mecquoise"},
    {"n": 84, "ar": "الانشقاق", "tr": "Al-Inshiqaq", "fr": "La Déchirure", "verses": 25, "type": "Mecquoise"},
    {"n": 85, "ar": "البروج", "tr": "Al-Buruj", "fr": "Les Constellations", "verses": 22, "type": "Mecquoise"},
    {"n": 86, "ar": "الطارق", "tr": "At-Tariq", "fr": "L'Astre Nocturne", "verses": 17, "type": "Mecquoise"},
    {"n": 87, "ar": "الأعلى", "tr": "Al-A'la", "fr": "Le Très-Haut", "verses": 19, "type": "Mecquoise"},
    {"n": 88, "ar": "الغاشية", "tr": "Al-Ghashiyah", "fr": "L'Enveloppante", "verses": 26, "type": "Mecquoise"},
    {"n": 89, "ar": "الفجر", "tr": "Al-Fajr", "fr": "L'Aube", "verses": 30, "type": "Mecquoise"},
    {"n": 90, "ar": "البلد", "tr": "Al-Balad", "fr": "La Cité", "verses": 20, "type": "Mecquoise"},
    {"n": 91, "ar": "الشمس", "tr": "Ash-Shams", "fr": "Le Soleil", "verses": 15, "type": "Mecquoise"},
    {"n": 92, "ar": "الليل", "tr": "Al-Layl", "fr": "La Nuit", "verses": 21, "type": "Mecquoise"},
    {"n": 93, "ar": "الضحى", "tr": "Ad-Duha", "fr": "Le Jour Montant", "verses": 11, "type": "Mecquoise"},
    {"n": 94, "ar": "الشرح", "tr": "Ash-Sharh", "fr": "L'Ouverture", "verses": 8, "type": "Mecquoise"},
    {"n": 95, "ar": "التين", "tr": "At-Tin", "fr": "Le Figuier", "verses": 8, "type": "Mecquoise"},
    {"n": 96, "ar": "العلق", "tr": "Al-'Alaq", "fr": "L'Adhérence", "verses": 19, "type": "Mecquoise"},
    {"n": 97, "ar": "القدر", "tr": "Al-Qadr", "fr": "La Destinée", "verses": 5, "type": "Mecquoise"},
    {"n": 98, "ar": "البينة", "tr": "Al-Bayyinah", "fr": "La Preuve", "verses": 8, "type": "Médinoise"},
    {"n": 99, "ar": "الزلزلة", "tr": "Az-Zalzalah", "fr": "La Secousse", "verses": 8, "type": "Médinoise"},
    {"n": 100, "ar": "العاديات", "tr": "Al-'Adiyat", "fr": "Les Coursiers", "verses": 11, "type": "Mecquoise"},
    {"n": 101, "ar": "القارعة", "tr": "Al-Qari'ah", "fr": "Le Fracas", "verses": 11, "type": "Mecquoise"},
    {"n": 102, "ar": "التكاثر", "tr": "At-Takathur", "fr": "La Course aux Richesses", "verses": 8, "type": "Mecquoise"},
    {"n": 103, "ar": "العصر", "tr": "Al-'Asr", "fr": "Le Temps", "verses": 3, "type": "Mecquoise"},
    {"n": 104, "ar": "الهمزة", "tr": "Al-Humazah", "fr": "Les Calomniateurs", "verses": 9, "type": "Mecquoise"},
    {"n": 105, "ar": "الفيل", "tr": "Al-Fil", "fr": "L'Éléphant", "verses": 5, "type": "Mecquoise"},
    {"n": 106, "ar": "قريش", "tr": "Quraysh", "fr": "Quraysh", "verses": 4, "type": "Mecquoise"},
    {"n": 107, "ar": "الماعون", "tr": "Al-Ma'un", "fr": "L'Ustensile", "verses": 7, "type": "Mecquoise"},
    {"n": 108, "ar": "الكوثر", "tr": "Al-Kawthar", "fr": "L'Abondance", "verses": 3, "type": "Mecquoise"},
    {"n": 109, "ar": "الكافرون", "tr": "Al-Kafirun", "fr": "Les Mécréants", "verses": 6, "type": "Mecquoise"},
    {"n": 110, "ar": "النصر", "tr": "An-Nasr", "fr": "Les Secours", "verses": 3, "type": "Médinoise"},
    {"n": 111, "ar": "المسد", "tr": "Al-Masad", "fr": "Les Fibres", "verses": 5, "type": "Mecquoise"},
    {"n": 112, "ar": "الإخلاص", "tr": "Al-Ikhlas", "fr": "Le Monothéisme Pur", "verses": 4, "type": "Mecquoise"},
    {"n": 113, "ar": "الفلق", "tr": "Al-Falaq", "fr": "L'Aube Naissante", "verses": 5, "type": "Mecquoise"},
    {"n": 114, "ar": "الناس", "tr": "An-Nas", "fr": "Les Hommes", "verses": 6, "type": "Mecquoise"},
]

# Récitateurs disponibles — chaque entrée contient son propre template d'URL
# (chaque CDN a son format). Validé manuellement le 2026-05-26.
RECITERS = [
    {
        "id": "alafasy",
        "name": "Mishary Rashid Alafasy",
        "country": "Koweït",
        "url": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/{n}.mp3",
    },
    {
        "id": "abdulbasit",
        "name": "Abdul Basit Abdul Samad",
        "country": "Égypte",
        "url": "https://cdn.islamic.network/quran/audio-surah/128/ar.abdulbasitmurattal/{n}.mp3",
    },
    {
        "id": "minshawi",
        "name": "Mohamed Siddiq Al-Minshawi",
        "country": "Égypte",
        "url": "https://download.quranicaudio.com/quran/muhammad_siddeeq_al-minshaawee/{n3}.mp3",
    },
    {
        "id": "sudais",
        "name": "Abdurrahman As-Sudais",
        "country": "Arabie Saoudite",
        "url": "https://download.quranicaudio.com/quran/abdurrahmaan_as-sudays/{n3}.mp3",
    },
    {
        "id": "shaatree",
        "name": "Abu Bakr Ash-Shaatree",
        "country": "Arabie Saoudite",
        "url": "https://download.quranicaudio.com/quran/abu_bakr_ash-shaatree/{n3}.mp3",
    },
    {
        "id": "husary",
        "name": "Mahmoud Khalil Al-Husary",
        "country": "Égypte",
        "url": "https://server13.mp3quran.net/husr/{n3}.mp3",
    },
    {
        "id": "maher",
        "name": "Maher Al-Muaiqly",
        "country": "Arabie Saoudite",
        "url": "https://server12.mp3quran.net/maher/{n3}.mp3",
    },
]


def get_audio_url(surah_n: int, reciter_id: str = "alafasy") -> str:
    """Résout l'URL audio en utilisant le template propre à chaque récitateur."""
    rec = next((r for r in RECITERS if r["id"] == reciter_id), RECITERS[0])
    return rec["url"].format(n=surah_n, n3=f"{surah_n:03d}")
